inveniosoftware/pytest-invenio

- pytest_invenio/fixtures.py
- pytest_invenio/plugin.py
- requirements-devel.txt
- tests/test_fixtures.py
* Fixes issue with output from the appplication logger not being
captured by the Click test runner due to changes in Flask's logging
handling in v0.13/1.0
> fixtures: click logging output fix

- pytest_invenio/fixtures.py
> fixtures: move elasticsearch import into a function

- pytest_invenio/fixtures.py
- setup.py
> fixtures: fix conflict with celery_config

- CHANGES.rst
- pytest_invenio/version.py
> release: v1.0.6

- setup.py
tested with clean invenio-instance 
(closes #26 )
> global: urllib3 version bump

- CHANGES.rst
- pytest_invenio/__init__.py
- pytest_invenio/version.py
> release: v1.1.0

- pytest_invenio/fixtures.py
- pytest_invenio/plugin.py
- setup.py
- tests/conftest.py
- tests/test_fixtures.py
Adds fixture for creating default Location,
Adds fixture for creating Bucket from direcotry with files.
closes #2
> fixtures: Adds fixtures for files

- .travis.yml
- CHANGES.rst
- pytest_invenio/version.py
- setup.py
- tests/test_fixtures.py
> global: update python dependencies

- CHANGES.rst
- pytest_invenio/version.py
> Release v1.3.1

- CHANGES.rst
- pytest_invenio/version.py
- setup.py
@inveniosoftware/architects @diegodelemos Should this be a minor version bump? or still a patch?
> add docker-services-cli

- pytest.ini
- pytest_invenio/__init__.py
- pytest_invenio/fixtures.py
- pytest_invenio/plugin.py
- run-tests.sh
- tests/test_fixtures.py
* Adds a new entry_points fixture which can inject extra entry points
during application loading to avoid having to manually registering
features.
> fixtures: new entry_points fixture

- .github/workflows/tests.yml
- constraints-min.txt
- constraints-pypi.txt
- pytest_invenio/fixtures.py
- pytest_invenio/user.py
- tests/conftest.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> users: add support for all user properties

- pytest_invenio/user.py
- closes https://github.com/inveniosoftware/invenio-communities/issues/536
> users: commit session through datastore

- pytest_invenio/__init__.py
- pytest_invenio/fixtures.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> fixtures: apply fix for flask-login

- pytest_invenio/fixtures.py
:heart: Thank you for your contribution!
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
> fixtures: disable rate-limiting in config

- pytest_invenio/user.py
* closes https://github.com/zenodo/zenodo-rdm/issues/284
> user: fix identity id

- .github/actions/pre-install/action.yml
- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- pytest_invenio/fixtures.py
- pytest_invenio/plugin.py
- tests/test_fixtures.py
* Adds a new fixtures to handle the `SEARCH_HOSTS` config from
the environment.
> fixtures: add "search_hosts"

- CHANGES.rst
- pytest_invenio/__init__.py
- pytest_invenio/fixtures.py
- pytest_invenio/plugin.py
- run-tests.sh
- tests/test_fixtures.py
I got annoyed with unhygienic app config changes.
> fixtures: add set_tmp_config

- .github/workflows/pypi-publish.yml
- .github/workflows/tests.yml
- CHANGES.rst
- pytest_invenio/__init__.py
- setup.cfg
:heart: Thank you for your contribution!
* `snowballstemmer` is dependency of the deprecated/unmaintained
`pydocstyle` module. The v3.0.0 release of `snowballstemmer`
introduces a breaking change.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as …
> installation: pin snowballstemmer to <3.x

- pytest_invenio/fixtures.py
* since some packages are still using importlib_metadata those tests are
breaking now. in the long run those packages should be updated to use
importlib.metadata but this commit enables a faster/easier transition
> fix: importlib_metadata legacy
